In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow_adopter import *
from sequence_transfomer import *
from time_series_transformer import Time_Series_Transformer

In [1]:
df = pd.read_csv('../Data/Train/sales_train_validation.csv')
dimList = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']
df = df.drop(['id'] ,axis =1)

NameError: name 'pd' is not defined

In [ ]:
fe = Time_Series_Transformer(df,dimList,seqTransformerList = [])
gen = fe.np_to_time_tensor_generator(30)

In [ ]:
tfg = TFRecord_Generator("../Data/Train/tfg2.tfRecord")
tfg.write_tfRecord(gen)

In [5]:
dataset = tfg.make_tfDataset()

In [6]:
len(list(dataset))

30490

In [7]:
list(dataset.take(1))

[{'item_id': <tf.Tensor: id=853779, shape=(1883, 1), dtype=float32, numpy=
  array([[1437.],
         [1437.],
         [1437.],
         ...,
         [1437.],
         [1437.],
         [1437.]], dtype=float32)>,
  'dept_id': <tf.Tensor: id=853778, shape=(1883, 1), dtype=float32, numpy=
  array([[3.],
         [3.],
         [3.],
         ...,
         [3.],
         [3.],
         [3.]], dtype=float32)>,
  'cat_id': <tf.Tensor: id=853777, shape=(1883, 1), dtype=float32, numpy=
  array([[1.],
         [1.],
         [1.],
         ...,
         [1.],
         [1.],
         [1.]], dtype=float32)>,
  'store_id': <tf.Tensor: id=853782, shape=(1883, 1), dtype=float32, numpy=
  array([[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]], dtype=float32)>,
  'state_id': <tf.Tensor: id=853781, shape=(1883, 1), dtype=float32, numpy=
  array([[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]], dtype=float32